(declare (usual-integrations))

(define (popcount x)
  (let loop ((x x) (c 0))
    (if (fix:zero? x)
    c
    (loop (fix:lsh x -1) (if (fix:zero? (fix:and 1 x)) c (fix:1+ c))))))

(define-structure hamt-empty)
(define-structure hamt-bitmap bitmap vector) ;; bitmap vector
(define-structure hamt-leaf key value) ;; key value

(define subkey-mask #xF)
(define (mask-index b m) (popcount (fix:and b (fix:-1+ m))))
(define (mask k s) (fix:lsh 1 (subkey k s)))
(define (subkey k s) (fix:and (fix:lsh k (fix:- 0 s)) subkey-mask))
(define bits-per-subkey 4)

(define (lookup k s t sc fc)
  (cond ((hamt-empty? t) (fc))
        ((hamt-leaf? t)
         (if (fix:= (hamt-leaf-key t) k)
           (sc (hamt-leaf-value t))
           (fc)))
        ((hamt-bitmap? t)
         (let ((m (mask k s))
               (b (hamt-bitmap-bitmap t)))
           (if (fix:= (fix:and b m) 0)
             (fc)
             (lookup k
                     (fix:+ s bits-per-subkey)
                     (vector-ref (hamt-bitmap-vector t)
                                 (mask-index b m))
                     sc
                     fc))))
        (else (error "invalid datatype passed to lookup"))))

(define (hamt-lookup k t success-continuation fail-continuation)
  (lookup k 0 t success-continuation fail-continuation))

(define (insert kx s x t)
  (cond ((hamt-empty? t) (make-hamt-leaf kx x))
        ((hamt-leaf? t)
         (let ((ky (hamt-leaf-key t))
               (y  (hamt-leaf-value t)))
           (if (fix:= ky kx)
             (make-hamt-leaf kx x)
             (insert kx s x (make-hamt-bitmap (mask ky y) (vector t))))
           ))
        ((hamt-bitmap? t)
         (let* ((b (hamt-bitmap-bitmap t))
                (v (hamt-bitmap-vector t))
                (m (mask kx s))
                (i (mask-index b m)))
           (if (fix:= (fix:and b m) 0)
             (let* ((l (make-hamt-leaf kx x))
                    (vp (vector-append (vector-head v i) (vector l) (vector-tail v i)))
                    (bp (fix:or b m)))
               (make-hamt-bitmap bp vp)
               )
             (let* ((st (vector-ref v i))
                    (stp (insert kx (+ s bits-per-subkey) x st))
                    (vp (vector-copy v)))
               (vector-set! vp i stp)
               (make-hamt-bitmap b vp)
               )
             )
           ))
        (else (error "invalid datatype passed to insert"))
        )
  )

(define (hamt-insert k v t) (insert k 0 v t))
